---
title: "nba2018-dictionary"
author: "Mindy Dai"
date: "10/5/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Data Dictionary

*This data dictionary describes different players in the NBA, with each player in each row.*

It comes from this [website](www.basketball-reference.com). This is a [sample link](https://www.basketball-reference.com/teams/GSW/2018.html) for the data source of the GS Warriors.

Listed below are the variables in this data set, including their names, a description, type, unit of measurement (if applicable), and possible missing values.

- player: first and last names of player, *character*, no missing values
- number: number on jersey, *numeric*, no missing values
- team: 3-letter team abbreviation, *character*, no missing values
- position: player’s position, *character*, no missing values
- height: height in feet-inches, *character*, no missing values
- weight: weight in pounds, *numeric*, no missing values
- birth_date: date of birth (“Month day, year”), *character*, no missing values
- country: 2-letter country abbreviation, *character*, no missing value
- experience: years of experience in NBA (a value of R means rookie), *numeric*, no missing values
- college: the college in USA they attended, *character*, no missing values
- salary: player salary in dollars
- rank: rank of player in his team
- age: age of Player at the start of February 1st of that season
- games: games played during regular season
- sames_started: games started
- minutes:minutes played during regular season
- field_goals: field goals made
- field_goals_atts: field goals attempted
- field_goals_perc: field goal percentage
- points3: 3-Point field goals made
- points3_atts: 3-point field goals attempted
- points3_perc: 3-point field percentage
- points2: 2-point field goals
- points2_atts: 2-point field goals attempted
- points2_perc: 2-point field goal percentage
- effective_field_goal_perc: Effective Field Goal percentage
- points1: free throws made
- points1_atts: free throws attempted
- points1_perc: free throw percentage
- off_rebounds: number of offensive rebounds
- def_rebounds: number of defensive rebounds
- assists: number of assists
- steals: number of steals
- blocks: number of blocks
- turnovers: number of turnovers
- fouls: number of fouls
- points: total points made
